version: '3'
services:
  mysql-standalone1:
    image: 'mysql:5.6'
    environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_USER=root
     - MYSQL_PASSWORD=
     - MYSQL_DATABASE=tickets_db
    ports:
    - "3307:3307"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
    - "8080:8080"

    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
    - mysql-standalone1
